### ISSUE TITLE
OpenLyrics support

### ISSUE THREAD

**Issue by tgc-dk** [FiniteLooper/LyricConverter#4]
Please consider adding support for the OpenLyrics XML format: http://openlyrics.info/

**Comment by FiniteLooper** [comment]
@tgc-dk Well... it took me a few years to find the time, but LyricConverter has been rewritten and support for OpenLyrics is now there!

**Comment by tgc-dk** [comment]
As they say, all things come to those who wait 😄
Great job 👍

**Comment by FiniteLooper** [comment]
Also as a follow up (in case you're interested) I've moved the OpenLyrics file parsing into its own library: https://github.com/FiniteLooper/OpenLyrics-parser

LyricConverter now uses this.
